# You can find the default config with description of parameters here:
# https://github.com/arboriginal/SCT-DeathPosTracker/blob/master/src/settings.yml
#
# Permissions for this tracker are listed here:
# https://github.com/arboriginal/SCT-DeathPosTracker/blob/master/README.md#permissions

settings:
  check_update: true # If true, when you (re)load the plugin, it try to check if a new version is available

  symbol: "§d§l☠" # Symbol displayed on the compass to represent this kind of trackers positions.
  temp:   "☙"    # Advanced: Symbol temporary used by the plugin, must be unique, 1 char and not used in "symbol".

  keep_position: 900 # (seconds) Time the last death location stays available

  auto_activated: true # If true, the tracker is automatically activated when a position is created
  auto_disabled: 5 # If player closer than this (in blocks) from the target, the tracking stop automatically (0 to disable).

  # Those parameters are used to highlight active targets when you facing them
  hl_angle: 0        # Angle in degree (integer) centered on compass middle point to be considered as faced (for example 30 means from 60° to 120°)
  hl_symbol: "§b§l☠" # Symbol displayed on the compass to represent active targets you are facing (require hl_angle > 0)
  hl_temp: "♴"       # Advanced: Symbol temporary used by the plugin (only used when hl_angle > 0)

locales:
  en:
    name: "death" # Only use alphabetic and numeric values, not space

    list: "{prefix}&rDeath coordinates: {list}&r."
    list_coord: "&6x: &c{x} &r/ &6z: &c{z}"
    list_empty: "{prefix}&rNo death coordinates."

    START: "{prefix}&6You are now tracking your &elast death&6 position."
    STOP: "{prefix}&6You no longer track your &elast death&6 position."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Show your last death coordinates.
      START: |
        &r- &c/{command} &e{tracker} &6{START}
        &7  Begin the tracking of your last death coordinate.
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP}
        &7  End the tracking of your last death coordinate.

    target_auto_disabled: "{prefix}&3You've reached &byour death place&3, tracking disabled."
    target_expired: "{prefix}&3Your &bdeath place&3 tracking has expired."

  fr:
    name: "mort" # N'utilise que des chiffres et des lettres, pas d'espace

    list: "{prefix}&rDernière mort: {list}&r."
    list_coord: "&6x: &c{x} &r/ &6z: &c{z}"
    list_empty: "{prefix}&rPas de coordinées de mort."

    START: "{prefix}&6Tu pistes maintenant &eta dernière mort&6."
    STOP: "{prefix}&6Tu ne pistes plus &eta dernière mort&6."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Affiche les coordonnées de ta dernière mort.
      START: |
        &r- &c/{command} &e{tracker} &6{START}
        &7  Démarre le pistage de ta dernière mort.
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP}
        &7  Arrête le pistage de ta dernière mort.

    target_auto_disabled: "{prefix}&3Tu as atteint &bton lieu de mort&3, pistage désactivé."
    target_expired: "{prefix}&3Le tracking de &bton lieu de mort&3 a expiré."
